### ISSUE TITLE
各タスクに日付を設定できる

### ISSUE THREAD

**Issue by donchan922** [donchan922/rails-todo#2]

**Comment by Saigodon** [comment]
@donchan922 
とりあえず日付を入れられる枠は作った。カンでつくったから内容はわからん。
DBかわったからrails db:migrateかrails db:migrate:resetがいるかも

**Comment by donchan922** [comment]
@Saigodon おお！ええやん。日付をカレンダーから選択できたり、バリデーション機能の追加もこんどやってみるか。
