### ISSUE TITLE
日付カレンダーで選択できるようにする

### ISSUE THREAD

**Issue by Saigodon** [donchan922/rails-todo#5]

**Comment by donchan922** [comment]
@Saigodon でけた。Gem追加したので、bundle installよろ。

**Comment by donchan922** [comment]
@Saigodon ちょいまち。編集画面だけ実装して、新規登録画面に機能つけるの忘れた。あげなおすわ。

**Comment by donchan922** [comment]
@Saigodon あげなおした。ためしてみそ。

**Comment by Saigodon** [comment]
@ @donchan922 
確認したわ。やるやんけ。どうやったんや

**Comment by donchan922** [comment]
@Saigodon カレンダー出してくれるGemを追加して、あとはjavascriptで日付選択時に処理呼び出してやればええんや。rubyというよりかはjavascript（jQuery）の処理やな。詳しくはコミットログ見てくれたらだいたいわかるはず。

**Comment by donchan922** [comment]
@Saigodon 今回の機能追加でわかったんやけど、railsではapp/assets配下にjavascriptやcssファイルを置くと勝手にそいつら読み込んでくれるみたい。フレームワークって感じ。
