### ISSUE TITLE
バリデーション機能追加

### ISSUE THREAD

**Issue by Saigodon** [donchan922/rails-todo#6]

**Comment by Saigodon** [comment]
@donchan922 
とりあえず空白禁止だけ入れた。
コピペしただけやから相変わらずなぜ動いているのかわからんわ

**Comment by donchan922** [comment]
@Saigodon ええやん。だんだんわかってくるんちゃう。あと、編集画面にはバリデートエラーメッセージでえへんから修正してほしいー。

**Comment by Saigodon** [comment]
@donchan922 
実はPUSH直前できづいてた。修正しました。

**Comment by donchan922** [comment]
@Saigodon おｋ
